name: Release to github packages

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      packages: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Building core
        run: |
          npm ci
          npm run compile
        working-directory: ./core

      - name: Building test
        run: |
          npm i ../core
          npm ci
          npm run compile
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./test

      - name: Building core tests
        run: |
          npm i ../core
          npm ci
          npm run compile
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ./core-tests

      - name: Running core tests
        run: npm run --silent run mocha-json 1>results.json 2>results-stderr.log
        working-directory: ./core-tests
        
      - name: Archive test results
        uses: actions/upload-artifact@v4
        with:
          name: test-result-report
          path: ./core-tests/results*

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests
          path: ./core-tests/results.json
          reporter: mocha-json

  publish-core:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check core version vs registry
        id: version_check
        uses: dupy-ts/check-package-version@main
        with:
          path: ./core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.version_check.outputs.committed-version }}"
            echo "Retrieved version: ${{ steps.version_check.outputs.retrieved-version }}"
            echo "Has been published: ${{ steps.version_check.outputs.is-published }}"

      - name: Publish core
        if: steps.version_check.outputs.is-new-version == 'true' || steps.version_check.outputs.is-published == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run compile
          npm publish
        working-directory: ./core

  publish-node:
    needs: publish-core
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check node version vs registry
        id: version_check
        uses: dupy-ts/check-package-version@main
        with:
          path: ./node
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.version_check.outputs.committed-version }}"
            echo "Retrieved version: ${{ steps.version_check.outputs.retrieved-version }}"
            echo "Has been published: ${{ steps.version_check.outputs.is-published }}"

      - name: Publish node
        if: steps.version_check.outputs.is-new-version == 'true' || steps.version_check.outputs.is-published == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish
        working-directory: ./node

  publish-apilib:
    needs: publish-node
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check node version vs registry
        id: version_check
        uses: dupy-ts/check-package-version@main
        with:
          path: ./apilib
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.version_check.outputs.committed-version }}"
            echo "Retrieved version: ${{ steps.version_check.outputs.retrieved-version }}"
            echo "Has been published: ${{ steps.version_check.outputs.is-published }}"

      - name: Publish package
        if: steps.version_check.outputs.is-new-version == 'true' || steps.version_check.outputs.is-published == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish
        working-directory: ./apilib
        
  publish-test:
    needs: publish-core
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check node version vs registry
        id: version_check
        uses: dupy-ts/check-package-version@main
        with:
          path: ./test
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Echo versions
        run: |
            echo "Committed version: ${{ steps.version_check.outputs.committed-version }}"
            echo "Retrieved version: ${{ steps.version_check.outputs.retrieved-version }}"
            echo "Has been published: ${{ steps.version_check.outputs.is-published }}"

      - name: Publish package
        if: steps.version_check.outputs.is-new-version == 'true' || steps.version_check.outputs.is-published == 'false'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run compile
          npm publish
        working-directory: ./test
