name: Release core to github packages

on:
  push:
    branches: [ "master", "github-package-registry" ] #TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm run compile
        working-directory: ./core
      - run: |
          npm ci
          npm run compile
        working-directory: ./test
      - run: |
          npm ci
          npm run compile
        working-directory: ./core-tests
      - run: npm run run
        working-directory: ./core-tests

  publish-core:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          npm run compile
        working-directory: ./core
      - run: npm publish
        working-directory: ./core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-node:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: |
          npm ci
          npm run build
        working-directory: ./node
      - run: npm publish
        working-directory: ./node
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
