name: Release to github packages

on:
  push:
    branches: [ "master", "github-package-registry" ] #TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm ci
          npm run compile
        working-directory: ./core
      - run: |
          npm ci
          npm run compile
        working-directory: ./test
      - run: |
          npm ci
          npm run compile
        working-directory: ./core-tests
      - run: npm run run
        working-directory: ./core-tests

  publish-core:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check core version vs registry
        id: version_check
        uses: PostHog/check-package-version@v2
        with:
          path: ./core
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish core
        if: steps.version_check.outputs.is-new-version == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run compile
          npm publish
        working-directory: ./core

  publish-node:
    needs: publish-core
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Check node version vs registry
        id: version_check
        uses: PostHog/check-package-version@v2
        with:
          path: ./node
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish node
        if: steps.version_check.outputs.is-new-version == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          npm run build
          npm publish
        working-directory: ./node