name: Release node to github packages

on:
  push:
    branches: [ "master", "github-package-registry" ] #TODO!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: |
          node -v
          npm -v
          npm config get @aczwink:registry
          npm whoami --registry=https://npm.pkg.github.com || true
          npm view @aczwink/acts-util-core --registry=https://npm.pkg.github.com || true
          npm ci
          npm run compile
        working-directory: ./core
      - run: |
          npm ci
          npm run build
        working-directory: ./node
      - run: npm publish
        working-directory: ./node
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
